export enum ENV_ENUM {
  JWT_ACCESS_SECRET = "JWT_ACCESS_SECRET",
  JWT_ACCESS_EXPIRATION = "JWT_ACCESS_EXPIRATION",
  JWT_REFRESH_SECRET = "JWT_REFRESH_SECRET",
  JWT_REFRESH_EXPIRATION = "JWT_REFRESH_EXPIRATION",

  MYSQL_DATABASE_URL = "MYSQL_DATABASE_URL",
}
